### ISSUE TITLE
sed is bad

### ISSUE THREAD

**Issue by wcatz** [davidjb/turris-omnia-tls#2]
It would appear you sed command or the instructions are off.

# Edit this file and replace `domain.example.com` with your FQDN
sed -i 's/domain.example.com/your.domain.com/g' /etc/lighttpd/conf.d/lighttpd_custom.conf

**Comment by davidjb** [comment]
What's the issue you're having or error you're seeing and what environment?  The command is working for me in the latest TurrisOS.

**Comment by wcatz** [comment]
The wording in your instructions is backwards. 

Edit this file and replace domain.example.com with your FQDN Should be replace 'your.domain.com' instead.

Thank you

**Comment by davidjb** [comment]
Ah I see - good catch.  I meant the instruction to say that one needs to _edit_ `lighttpd_custom.conf` and replace the placeholders _inside_ the file, rather than replace the reference in the subsequent command.  I've made some edits to the README to improve the wording.  Thanks for the report!
